### PR TITLE
feature/mark-recipe-as-favorites

### PR DESCRIPTION
**Pull request by feivlinus**
Completed [Mark Recipes as Favorites#11](https://github.com/feivlinus/fork-yeah/issues/11)

### CODE REVIEW

**Review by luederb — CHANGES_REQUESTED** [review]
>

**Comment by luederb** [comment]
Great work 💪
Looks good to me! 
Was really interesting to understand all of your code. Had to clone it to my local VS Code though, to fully understand all the drilling routes etc ^^ But I learned a ton from reviewing your code. Nice work, Fork Yeah!🥳

**Review by luederb — APPROVED** [review]
Great work 💪
Looks good to me!
Was really interesting to understand all of your code. Had to clone it to my local VS Code though, to fully understand all the drilling routes etc ^^ But I learned a ton from reviewing your code. Nice work, Fork Yeah!🥳

**Comment by feivlinus** [comment]
@luederb Thank you for your kind words and your review <3

**Review by vlatkojuric — APPROVED** [review]
Approved

**Pull request merged**
