### PR TITLE
Feature/recipe details page

### PR DESCRIPTION
**Pull request by Shahab-Ziaeian**
We created the recipe details page and rendered the recipes picture, title, description, preparation time , ingredients. 
Furthermore we added a link for each recipe, which leads back to the overview of recipes. 
We also added a link for each recipe at the recipe list, which leads to the related details page.

### CODE REVIEW

**Review by BirkBee — CHANGES_REQUESTED** [review]
Hey Hey @Shahab-Ziaeian  @vlatkojuric and @feivlinus ! 🙌

Nice app and progress so far! 
I have some recommendations for you:
- You've written in your ac that your descriptions include a direction on how to cook your dishes, but there are no instructions. Maybe that is wanted at this point, but that's for you to decide
- Your wireframe looks a little different to what your app looks like so far. Maybe you could put the list of groceries next to your image.

Otherwise I'm very happy with your code and everything else in your app. The back Link works and everything is rendered 🙌 

I'm looking forward to see more of your fork-yeah app 🚀

**Comment by feivlinus** [comment]
> Hey Hey @Shahab-Ziaeian @vlatkojuric and @feivlinus ! 🙌
> 
> Nice app and progress so far! I have some recommendations for you:
> 
> * You've written in your ac that your descriptions include a direction on how to cook your dishes, but there are no instructions. Maybe that is wanted at this point, but that's for you to decide
> * Your wireframe looks a little different to what your app looks like so far. Maybe you could put the list of groceries next to your image.
> 
> Otherwise I'm very happy with your code and everything else in your app. The back Link works and everything is rendered 🙌
> 
> I'm looking forward to see more of your fork-yeah app 🚀

Hey Birk,

thank you for your Review!

- The description is the instruction how to cook something. Our dummy data just has some random text.
Good that you mention it. The dummy data will be changed when we progress further.

- Its only a wireframe. We did not finalize our design yet we focus on the features first and then define a design.

✌️

**Review by BirkBee — APPROVED** [review]
Okay, thank you very much for explaining🥳

LGTM ✅

**Review by BirkBee — APPROVED** [review]
LGTM 😋

**Review by feivlinus — APPROVED** [review]
Birk approved.

**Review by JessicaLoers — APPROVED** [review]
wel done. 🚀

**Pull request merged**
